using API.Extensions;
using MongoDB.Driver;
using MongoDB.Entities;
using Persistence.Data;
using API.Middleware;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();

builder.Services.AddDependencies(builder.Configuration);

var app = builder.Build();

// Configure the HTTP request pipeline.

// It is best practice to put this at the top of the pipeline so that it can catch exceptions generated by middleware below.
app.UseMiddleware<ExceptionMiddleware>();

//app.UseAuthorization();

app.MapControllers();

await DB.InitAsync("SearchDb", MongoClientSettings.FromConnectionString(builder.Configuration.GetConnectionString("MongoDbConnection")));
try
{
    await DbInitializer.InitDb();
} catch (Exception e)
{
    Console.WriteLine(e);
}

app.Run();
