version: '3.4'
name: carsapp
services:
  advertisement:
    container_name: advertisementService
    image: ${DOCKER_REGISTRY-}advertisement
    build:
      context: .
      dockerfile: src/Services/AdvertisementService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTP_PORTS=7777 
      - ConnectionStrings__DefaultConnection=Server=postgres-advertisement:5432;User Id=postgres;Password=postgrespw;Database=advertisement
      - IdentityServiceUrl=http://identity:80 
      - RabbitMq__Host=rabbitmq
      - ServiceName=advertisement
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - "7001:80"
      - "7777:7777"
    depends_on:
      - postgres-advertisement
      - rabbitmq
      - identity 

  search:
    container_name: searchService
    image: ${DOCKER_REGISTRY-}search
    build:
      context: .
      dockerfile: src/Services/SearchService/API/Dockerfile
    environment:
      - ServiceName=search
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://mongo:mongopw@mongodb 
    ports:
      - "7002:80"
    depends_on:
      - mongodb
      - rabbitmq

  offer:
    container_name: offerService
    image: ${DOCKER_REGISTRY-}offer
    build:
      context: .
      dockerfile: src/Services/OfferService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=postgres-offer:5432;User Id=postgres;Password=postgrespw;Database=offer
      - IdentityServiceUrl=http://identity:80
      - RabbitMq__Host=rabbitmq
      - ServiceName=offer 
      - GrpcAdvertisement=http://advertisement:7777
    ports:
      - "7003:80"
    depends_on:
      - postgres-offer
      - rabbitmq
      - identity 

  notification:
    container_name: notificationService
    image: ${DOCKER_REGISTRY-}notification
    build:
      context: .
      dockerfile: src/Services/NotificationService/Notification/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - RabbitMq__Host=rabbitmq
      - ServiceName=notification
    ports:
      - "7004:80"
    depends_on:
      - rabbitmq
  
  inventory:
    container_name: inventoryService
    image: ${DOCKER_REGISTRY-}inventory
    build:
      context: .
      dockerfile: src/Services/InventoryService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=postgres-inventory:5432;User Id=postgres;Password=postgrespw;Database=inventory
      - IdentityServiceUrl=http://identity:80
      - ServiceName=inventory
    ports:
      - "7005:80"
    depends_on:
      - postgres-inventory
      - identity

  postgres-advertisement:
    container_name: advertisementServiceDb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata-advertisement:/var/lib/postgresql

  postgres-offer:
    container_name: offerServiceDb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 6000:5432
    volumes:
      - pgdata-offer:/var/lib/postgresql
  
  postgres-inventory:
    container_name: inventoryServiceDb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 10000:5432
    volumes:
      - pgdata-inventory:/var/lib/postgresql

  pgadmin:
    container_name: postgresDbsUI
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgrespw
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-advertisement
      - postgres-identity

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb

  mongoexpress:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongo
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongopw
      - ME_CONFIG_BASICAUTH_USERNAME=mongoexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpresspw
    ports:
      - 8081:8081
    volumes:
      - mongoexpress:/var/lib/mongoexpress
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Services/IdentityService/Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=postgres-identity:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - "5000:80"
    depends_on:
      - postgres-identity

  postgres-identity:
    container_name: identityServiceDb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5001:5432
    volumes:
      - pg-identitydata:/var/lib/postgresql-identity

  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: src/Services/GatewayService/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "6001:80"

volumes:
  pgdata-advertisement:
  pgadmin-data:
  mongodata:
  mongoexpress:
  pg-identitydata:
  pgdata-offer:
  pgdata-inventory:

