version: '3.4'
name: carsapp
services:
  auctions:
    container_name: auctionsService
    image: ${DOCKER_REGISTRY-}auctions
    build:
      context: .
      dockerfile: src/Services/AuctionService/API/Dockerfile
    environment:
      - SERVICE_NAME=auctions
    depends_on:
      - postgres
      - rabbitmq

  search:
    container_name: searchService
    image: ${DOCKER_REGISTRY-}search
    build:
      context: .
      dockerfile: src/Services/SearchService/API/Dockerfile
    environment:
      - SERVICE_NAME=search
    depends_on:
      - mongodb
      - rabbitmq

  postgres:
    container_name: auctionsServiceDb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql

  pgadmin:
    container_name: auctionServiceDbUI
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgrespw
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb

  mongoexpress:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongo
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongopw
      - ME_CONFIG_BASICAUTH_USERNAME=mongoexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpresspw
    ports:
      - 8081:8081
    volumes:
      - mongoexpress:/var/lib/mongoexpress
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Services/IdentityService/Identity/Dockerfile

volumes:
  pgdata:
  pgadmin-data:
  mongodata:
  mongoexpress:
