version: '3.4'
name: carsapp
services:
  api:
    container_name: auctionsService
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Services/AuctionService/API/Dockerfile
    depends_on:
      - postgres
  postgres:
    container_name: auctionsServiceDb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
  pgadmin:
    container_name: auctionServiceDbUI
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  

volumes:
  pgdata:
  pgadmin-data:
