using Notification.Hubs;
using Notification.Configuration;
using Notification.Middleware;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDependencies(builder.Configuration);

var app = builder.Build();

// Configure the HTTP request pipeline.

// It is best practice to put this at the top of the pipeline so that it can catch exceptions generated by middleware below.
app.UseMiddleware<ExceptionMiddleware>();

//app.UseCors();

app.MapHub<NotificationHub>("/notification");

app.Run();